### ISSUE TITLE
gunicorn 21

### ISSUE THREAD

**Issue by benoitc** [benoitc/gunicorn#1195]
meta issue to track changes needed to release the version 21.  After [the talk I gave at the FOSDEM](https://speakerdeck.com/benoitc/gunicorn-more-than-a-wsgi-server) I thought it would be interesting to track the different tasks we need for the new version. Feedback and help is more than welcome.
## tasks
- [ ] release imsg
- [ ] add regression test to the supervision
- [ ] replace the temporary file notification system by imsg
- [ ] add/increase tests for the logging (if needed)
- [ ] handle logging via a separate process coupled with imsg
- [ ] add new Proc class
- [ ] add HTTP 2 support
- [x] remove all python2 compatibility bits (PR: #1764)

**Comment by benoitc** [comment]
cc @berkerpeksag @tilgovi

**Comment by dstufft** [comment]
What does:

> remove all python3 compatibility bits

Mean? That's not gunicorn dropping support for Python 3.x is it?

**Comment by benoitc** [comment]
@dstufft ah... fixed it. I meant python 2 of course :) Thanks!

**Comment by dstufft** [comment]
So, does that mean dropping support for Python 2.x then? :)

**Comment by benoitc** [comment]
@dstufft totally. New version will only support python 3. Python 2 will only have the maintenance updates on the 19.x branch.

**Comment by dstufft** [comment]
Cool. Thanks!

**Comment by Lukasa** [comment]
@benoitc For HTTP/2, if you're interested in supporting it using [hyper-h2](http://python-hyper.org/h2/) I may be able to spare some time to do help out with integration work.

**Comment by benoitc** [comment]
@dstufft we talk about that last year in #1029 :)

**Comment by benoitc** [comment]
@Lukasa nice! It seems to have the exact level of abstraction needed for gunicorn. Maybe we could sync each others next week on IRC when I'm back from the FOSDEM? I will toy with it in the mean time :)

**Comment by Lukasa** [comment]
@benoitc You bet! Come join us in #python-hyper on freenode whenever suits.

**Comment by tilgovi** [comment]
:+1:

**Comment by athoune** [comment]
and some abstractions for non http protocol, like Thrift-rpc? It's already doable with ugly hack with gunicorn 19.

**Comment by benoitc** [comment]
@Lukasa was busy last week. Let's try to discuss that on #gunicorn next week or your channel if you want to.

@athoune what would it requires?

**Comment by RyPeck** [comment]
@benoitc so gunicorn 20 will not support Python 2.7?

**Comment by benoitc** [comment]
@RyPeck Support for 2.x is not dropped. What it means is that gunicorn 19.X will get maintenance updates but no more new features, while gunicorn 20.x and sup will continue to evolve, just like python 2.x is vs 3.x. There may be from time to time backports anyway.

At least that the plan :) Any opinion is welcome.

**Comment by RyPeck** [comment]
@benoitc good to know - if you could codify that plan somewhere more obvious that would be great! In the mean time I'll update my relevant requirements files to `gunicorn<20` which should always get me the latest 19.x.y.

**Comment by wooparadog** [comment]
@athoune 

> and some abstractions for non http protocol, like Thrift-rpc? It's already doable with ugly hack with gunicorn 19.

IMO, if the abstractions in gunicorn holds relatively the same, it won't be that dirty for non http protocols. See our https://github.com/eleme/gunicorn_thrift/ , we'll keep up with gunicorn 20 once it's released.

**Comment by Code0x58** [comment]
It would be good to add to the README.md and docs of 19+ that 19.x is the last to support Python2 but will continue to be maintained.

**Comment by jimmywan** [comment]
Any news on a new release? Stumbled across this fix that I'd like to see released to the wild:
610596c9d93b3c9086becd6212ab4ba81d476dc4

**Comment by berkerpeksag** [comment]
@jimmywan Gunicorn 20 is not ready yet but we can indeed make a new 19.x release.

**Comment by benoitc** [comment]
@berkerpeksag i guess we can cut a release now. Then do some grooming Thoughts ? cc @tilgovi

**Comment by altaurog** [comment]
Just curious.  Do you have an ETA for release?  It looks like it has been about a year since the last release.  I would like to get #1616 into production.

**Comment by Code0x58** [comment]
@altaurog see #1634 for the next (19.8.0) release

**Comment by hugovk** [comment]
> remove all python2 compatibility bits

As a first step towards this, is there any interest in first dropping support for EOL Python versions: 2.6 and 3.2-3.3? They no longer receive security updates (or any updates) from the core Python team and they're little used.

Here's the pip installs for Gunicorn from PyPI for last month:

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |  43.17% |        310,345 |
| 3.6            |  27.45% |        197,303 |
| 3.5            |  25.37% |        182,372 |
| 3.4            |   3.83% |         27,540 |
| 3.7            |   0.07% |            504 |
| 2.6            |   0.06% |            397 |
| 3.3            |   0.05% |            348 |
| 3.2            |   0.00% |             27 |
| None           |   0.00% |              7 |

Source: `pypinfo --start-date -46 --end-date -19 --percent --pip --markdown gunicorn pyversion`

**Comment by berkerpeksag** [comment]
I doubt we have a lot of compatibility code for those EOL Pythons. We could probably get rid all of them (all pre 3.5 versions) in same PR

**Comment by berkerpeksag** [comment]
Oh, by the way, thanks for the installation stats!

**Comment by hugovk** [comment]
Here's a few more stats for good measure.

`$ pypinfo --start-date -46 --end-date -19 --percent --pip --markdown gunicorn system distro`

| system_name | distro_name                     | percent | download_count |
| ----------- | ------------------------------- | ------: | -------------: |
| Linux       | Debian GNU/Linux                |  49.80% |        352,524 |
| Linux       | Ubuntu                          |  24.38% |        172,604 |
| Linux       | None                            |   5.94% |         42,071 |
| Linux       | Alpine Linux                    |   5.92% |         41,902 |
| Linux       | Amazon Linux AMI                |   4.24% |         30,016 |
| Linux       | CentOS Linux                    |   3.88% |         27,471 |
| Linux       | debian                          |   2.89% |         20,454 |
| Darwin      | macOS                           |   1.41% |          9,965 |
| Windows     | None                            |   0.79% |          5,610 |
| Linux       | Red Hat Enterprise Linux Server |   0.74% |          5,255 |

`$ pypinfo --start-date -46 --end-date -19 --percent --pip --markdown gunicorn country`

| country | percent | download_count |
| ------- | ------: | -------------: |
| US      |  84.67% |        545,887 |
| IE      |   3.58% |         23,060 |
| DE      |   2.69% |         17,326 |
| FR      |   1.80% |         11,628 |
| GB      |   1.40% |          9,051 |
| CA      |   1.40% |          8,999 |
| AU      |   1.16% |          7,503 |
| NL      |   1.15% |          7,444 |
| RU      |   1.14% |          7,349 |
| JP      |   1.01% |          6,496 |

**Comment by benoitc** [comment]
removing support of python2 is planned for next major release.

However, one stats though you were forgetting is how much *I* were using
python2 ;) Hopefully not that much anymore.

**Comment by hugovk** [comment]
https://github.com/benoitc/gunicorn/pull/1764 has been merged which drops Python 2 support, and can be checked off the task list above.

**Comment by berkerpeksag** [comment]
@hugovk done!

**Comment by rollokb** [comment]
@benoitc what would have to change for HTTP2 support. Curious, because I'd love to help.

**Comment by vikramarsid** [comment]
@benoitc Any update on http/2 support?

**Comment by benoitc** [comment]
@vikramarsid once 20.0 is released I will provide a worker for it

**Comment by maximmarakov** [comment]
I have some error while upgrage my app from gunicorn 19.9 to 20.0. 
``` exec gunicorn -w 4 "api.wsgi:init_app()" ```
init_app() return the app flask instance
```
def init_app():
    app = Flask(__name__)
    app.register_blueprint(bp)
    return app
```
It work with 19.9 , but dont with 20.0
Text of error: ` Failed to find application object 'init_app()' in 'api.wsgi' `
This man have some trouble: https://stackoverflow.com/a/58809644/11321632

**Comment by tilgovi** [comment]
Would be great to rename this and get a milestone to track for 21.

**Comment by benoitc** [comment]
@tilgovi done. I think we should open a project and assign a bunch of tickets for it.

**Comment by tilgovi** [comment]
👍

**Comment by Svetlitski** [comment]
Is this issue dead? If so where is progress on HTTP/2 support being tracked now?

**Comment by Lepidax** [comment]
I am also very interested in the http/2 feature. Will it ever come? Any ETA?

**Comment by tilgovi** [comment]
Besides HTTP/2, what other big feature requests are there right now? Windows support is the other one I keep seeing, but no one has taken on that work, either.

**Comment by tilgovi** [comment]
I started a milestone: https://github.com/benoitc/gunicorn/milestones?with_issues=no

**Comment by AbdelazizSharaf001** [comment]
@benoitc I hope there is something for HTTP/2 or even an external addon [ version 20.0.4 ]

**Comment by 124bit** [comment]
HTTP/2 is very relevant request

**Comment by johnthagen** [comment]
@tilgovi Since [20.1.0 has already been released](https://pypi.org/project/gunicorn/20.1.0/), does [this milestone](https://github.com/benoitc/gunicorn/milestone/20) need to be renamed?

**Comment by boompig** [comment]
Hi all, it appears that this is the main tracking issue for adding HTTP/2 to gunicorn. As such, there doesn't appear to have been much progress for the past ~5 years. This is not meant as a criticism of the core team, just trying to read the issue history.

Are there any updates/work-arounds in terms of getting gunicorn ready for HTTP/2? Would it be helpful to have a separate issue tracking the HTTP/2 issue specifically?

**Comment by tilgovi** [comment]
If there isn't already an HTTP/2 issue, please feel free to open one. Thanks!

**Comment by johnthagen** [comment]
> If there isn't already an HTTP/2 issue, please feel free to open one. Thanks!

#1688 was opened for HTTP/2 support, but was closed in favor of this issue.

**Comment by johnthagen** [comment]
> Are there any updates/work-arounds in terms of getting gunicorn ready for HTTP/2?

Not sure what your deployment model is, but you can use HTTP/2 with a reverse proxy like NGINX, and run Gunicorn behind it over HTTP/1.1. This allows NGINX to handle the performance intensive side (HTTPS, HTTP/2, etc) and proxy the actual data to Gunicorn. If you deploy your applications via containers, it ends up be fairly simply to add a NGINX container using the default image published on Docker Hub: https://hub.docker.com/_/nginx

Articles like this provide an example for this: https://testdriven.io/blog/dockerizing-django-with-postgres-gunicorn-and-nginx/

**Comment by ssill2** [comment]
Hello, I've been looking on gunicorn.org and here for a list of versions that should be considered supported, and which should be considered EOL.  Is there a general guideline that  a major version will be supported for n months/years before being considered EOL? 
Thanks!

**Comment by benoitc** [comment]
@ssill2 new doc will describe the maintenance window and new cycle of updates.

**Comment by nog642** [comment]
Why was this closed? Is HTTP/2 support not going to be added?

**Comment by ViswanathB** [comment]
Looking for gunicorn http2, would this never be supported?

**Comment by benoitc** [comment]
@vikramarsid this shoudl be a separate ticket. Yes this will be suppoted.  I will provide informatiosn next week with some updates about the project.

**Comment by stekole** [comment]
> @vikramarsid this shoudl be a separate ticket. Yes this will be suppoted. I will provide informatiosn next week with some updates about the project.

any updates?

**Comment by zaksel** [comment]
Hi @benoitc, support of http2 would be much appreciated! I'm running into issues with the max-connections-per-server limit set to 6 parallel connections on chrome and hope to avoid this by using http2.

Thank you to you and all the other contributors for the nice work :)
