### ISSUE TITLE
Meta-Information needs update

### ISSUE THREAD

**Issue by pajod** [benoitc/gunicorn#3122]
- [ ] Are historically referenced [MAINTAINERS](https://github.com/benoitc/gunicorn/blob/master/MAINTAINERS) still active and posess permissions on GitHub?
- [x] There is no primary contact email mentioned in [Security.md](https://github.com/benoitc/gunicorn/security) - should stay in sync with [community.rst](https://github.com/benoitc/gunicorn/blob/master/docs/source/community.rst#security-issues)
  - https://github.com/benoitc/gunicorn/issues/3160
- [ ] Many triaged issues / planned changes need (updated) milestone
  - https://github.com/benoitc/gunicorn/issues?q=is%3Aopen+is%3Aissue+milestone%3A22.0
-  [ ] many existing PR are stuck with no or outdated "what is missing to move this forward" comment
   - and possibly too few PRs and issues are closed with "this is not moving forward for this reason" clarification
- [x] Typo in the [Security.md](https://github.com/benoitc/gunicorn/security)
   - sorry, my bad! I missed the trailing S: https://devguide.python.org/versions/
   - https://github.com/benoitc/gunicorn/pull/3123
- [ ] Last entry in [NOTICE](https://github.com/benoitc/gunicorn/blob/master/NOTICE) reference is unclear
  -    maybe util.py/_waitfor() reference and cpython/Lib/test/support/os_helper.py now (can that be deleted eventually?)
- [ ] build infrastructure is not well documented.
  - Should what is partially already done - referencing test dependencies via extras be done everywhere, no requirements*.txt whatsoever?
  - maybe [putting it all in in a CI file referencing the Python Packaging Authority github action](https://github.com/marketplace/actions/pypi-publish) would both document it and ensure we do not reinvent wheels (pun intended)
  - https://github.com/benoitc/gunicorn/pull/3134
 - [ ] Is the Makefile still of any use?
    - the sphinx one is out of date, it does not understand the `dummy` target (running `sphinx-quickstart --extensions=gunicorn_ext` gave one [one that does](https://github.com/pajod/gunicorn/blob/2ce4741ae48a72af4d4ee005ba41cdb3471215e6/docs/Makefile#L49))
    - test target bitrotted from setuptools deprecations, see https://github.com/benoitc/gunicorn/pull/3387
- [ ] supported OS should be clarified, and preferably strictly based on what is really tested in Github CI
   - Linux works well, Mac sort of works (no pipe2()), cygwin and WSL1 are weird about filesystem & socket operation edge cases, WSL2 *probably* works as good as Linux (broken by CLOCK_REALTIME fun) but is unavailable on Github CI
  - we *can* test WSL via appveyor right now, like [its not even particularly complex or slow](https://ci.appveyor.com/project/pajod/gunicorn/build/job/enh3hq7q80ya8cm9), its more a matter of whether anyone cares to look at failures
- [ ] I have not been able to use (==) the mentioned minimum (>=) gevent / eventlet versions.
   - The actual minimum supported version is easy enough to verify in CI to not miss that in the future.
   - https://github.com/benoitc/gunicorn/pull/3134
- [x] It is easy to forget `make -C docs html`
   - if we insist on keeping the duplication in-repo, we can and should CI-test
   - https://github.com/benoitc/gunicorn/pull/3217
- [ ] The main README.. in fact the also the full documentation lacks clear goal / non-goal statements
  - should probably point to https://peps.python.org/pep-3333/ and https://datatracker.ietf.org/doc/html/rfc9112 and promise to implement those reasonably well - and point out where we make our own notable choices.
  - ideas gathered here #3261
- [x] GitHub Projects feature is currently unused and should not be pointed to in docs
  - https://github.com/benoitc/gunicorn/pull/3391
